### ISSUE TITLE
App stuck on black screen?

### ISSUE THREAD

**Issue by NAEL2XD** [zdm65477730/NX-Activity-Log#3]
So I downloaded it, placed in sd:/switch/NX-Activity-Log, and then I placed the file there, when done and when I try to launch it, it just stays on black screen, idk why it does that, so if anyone knows a fix, please let me know.

I also tried to downgrade the app to 2 other releases, even downloaded the vanilla one which worked but didnt show titles because it wasnt updated, downgraded my Firmware, even my Atmosphere, and NONE work, I just wanna see what's in it...

Also I use these:

Firmware Version: ~~16.0.0~~ 19.0.1
Atmosphere Version: 1.8.0|E
App Version: Latest Release
SoC Type: Erista 

Is it because of this issue? I'm confused.

**Comment by NAEL2XD** [comment]
@zdm65477730 sorry for the ping but please do you know any solution??

**Comment by AlM2025** [comment]
Update your firmware to the latest version 19.0.1

**Comment by NAEL2XD** [comment]
> Update your firmware to the latest version 19.0.1

ok so i updated my switch to 19.0.1, updated the app again and it's still in black screen.

**Comment by NAEL2XD** [comment]
More info
![Screenshot_20241109_151745_Camera.png](https://github.com/user-attachments/assets/1af171fd-d288-4625-8a45-2087162890c5)

**Comment by AlM2025** [comment]
How do you run the app? From the user profile icon or from the Hebrew menu?

**Comment by NAEL2XD** [comment]
> How do you run the app? From the user profile icon or from the Hebrew menu?

from hb menu by launching album, user profile just crashes atmosphere

**Comment by AlM2025** [comment]
Try the following steps:

**On your SD card:**

1. Delete the folder atmosphere/contents/0100000000001013.

2. Make sure that the .nro file is in /switch/NX-Activity-Log/NX-Activity-Log.nro.

3. Start the console and test again.

**Comment by NAEL2XD** [comment]
> Try the following steps:
> 
> **On your SD card:**
> 
> 1. Delete the folder atmosphere/contents/0100000000001013.
> 2. Make sure that the .nro file is in /switch/NX-Activity-Log/NX-Activity-Log.nro.
> 3. Start the console and test again.

did all 3 of the steps, and still a black screen

**Comment by AlM2025** [comment]
Even when running the app in full system mode by overriding a game, the screen remains blank!?

**Comment by NAEL2XD** [comment]
> Even when running the app in full system mode by overriding a game, the screen remains blank!?

even if it isn't in applet mode, it still remains blank.

**Comment by zdm65477730** [comment]
I have no such issue in my OLED NS, is it the other sysmodule break the functionality?

**Comment by NAEL2XD** [comment]
> I have no such issue in my OLED NS, is it the other sysmodule break the functionality?

I'm really new to modding but what is a sysmodule and where is it stored?

**Comment by NAEL2XD** [comment]
try releasing a debug logging version so it can log crashes and where i went, so i can send the logs

**Comment by Fuffelpups** [comment]
I have the same problem.

Erista Switch with Atmosphère and hekate.

I disabled all overlays and sysmodules and still get a black screen.

**Comment by zdm65477730** [comment]
Unfortunely, I have no Eersta HW for testing.
Did you delete all files under atmosphere/contents/0100000000001013/ and config/NX-Activity-Log/ and reproduce the issue?

**Comment by Fuffelpups** [comment]
I deleted the folder 0100000000001013 and the config folder yesterday, the problem remains.

**Comment by NAEL2XD** [comment]
> Unfortunely, I have no Eersta HW for testing. Did you delete all files under atmosphere/contents/0100000000001013/ and config/NX-Activity-Log/ and reproduce the issue?

i did delete both of them, still a black screen. + someone asked this ago https://github.com/zdm65477730/NX-Activity-Log/issues/3#issuecomment-2466275949

**Comment by NAEL2XD** [comment]
weird part is this one (https://github.com/tallbl0nde/NX-Activity-Log/releases/tag/v1.4.0) does launch fine but this fork does launch on a black screen

**Comment by AlM2025** [comment]
Clear the folder config/NX-Activity-Log

**Comment by NAEL2XD** [comment]
> Clear the folder config/NX-Activity-Log

You know I did remove it.

**Comment by Fuffelpups** [comment]
I backed my files up and tried a fresh install only Atmosphère and hekate nothing else, still a black screen with NX-Activity-Log v1.5.1.

**Comment by NAEL2XD** [comment]
Does anyone have a fix for it?

**Comment by zdm65477730** [comment]
@NAEL2XD , please download and run the debug tool, then upload the trace file:
https://github.com/zdm65477730/PlayEventParser/releases/download/v1.0/PlayEventDumper.zip

**Comment by NAEL2XD** [comment]
> @NAEL2XD , please download and run the debug tool, then upload the trace file: https://github.com/zdm65477730/PlayEventParser/releases/download/v1.0/PlayEventDumper.zip

[playlog[2].txt](https://github.com/user-attachments/files/17775234/playlog.2.txt)
6 mb file (yeah i played a lot of it)

**Comment by Fuffelpups** [comment]
> @NAEL2XD , please download and run the debug tool, then upload the trace file: https://github.com/zdm65477730/PlayEventParser/releases/download/v1.0/PlayEventDumper.zip

[playlog.txt](https://github.com/user-attachments/files/17775527/playlog.txt)

**Comment by zdm65477730** [comment]
Please download the debug version and run.
Please wait for a while and exit, then upload the log file(sd:/switch/NX-Activity-Log/debug.log).
[NX-Activity-Log.zip](https://github.com/user-attachments/files/17777810/NX-Activity-Log.zip)

**Comment by NAEL2XD** [comment]
> Please download the debug version and run. Please wait for a while and exit, then upload the log file(sd:/switch/NX-Activity-Log/debug.log). [NX-Activity-Log.zip](https://github.com/user-attachments/files/17777810/NX-Activity-Log.zip)

```log
[debug] Services started and Crul init finished!
[debug] Read config file finished!
[debug] Set language finished!
```
this is all it sent

**Comment by zdm65477730** [comment]
Insteating, I added more debug trace in the new debug version, please have a try:
[NX-Activity-Log.zip](https://github.com/user-attachments/files/17778329/NX-Activity-Log.zip)

**Comment by NAEL2XD** [comment]
> Insteating, I added more debug trace in the new debug version, please have a try: [NX-Activity-Log.zip](https://github.com/user-attachments/files/17778329/NX-Activity-Log.zip)

```
[debug] Services started and Crul init finished!
[debug] Read config file finished!
[debug] Set language finished!
[debug] readPlayDataFromImport() enter
[debug] pdmqryGetAvailablePlayEventRange(), rc=0
[debug] pdmqryQueryPlayEvent(), rc=0
[debug] pdmqryQueryPlayEvent(), rc=0
[debug] pdmqryQueryPlayEvent(), rc=0
[debug] pdmqryQueryPlayEvent(), rc=0
[debug] pdmqryQueryPlayEvent(), rc=0
[debug] pdmqryQueryPlayEvent(), rc=0
[debug] pdmqryQueryPlayEvent(), rc=0
[debug] pdmqryQueryPlayEvent(), rc=0
[debug] pdmqryQueryPlayEvent(), rc=0
[debug] pdmqryQueryPlayEvent(), rc=0
[debug] pdmqryQueryPlayEvent(), rc=0
[debug] pdmqryQueryPlayEvent(), rc=0
```

rest of them are same

**Comment by NAEL2XD** [comment]
[debug.log](https://github.com/user-attachments/files/17778408/debug.log)
true debug (almost all of them are [debug] pdmqryQueryPlayEvent(), rc=0)

**Comment by zdm65477730** [comment]
@NAEL2XD , seems that you have too many game data entries, loading them took a lot of time, and this happened before creating the window.
I need to think about how to solve it.

**Comment by NAEL2XD** [comment]
> @NAEL2XD , seems that you have too many game data entries, loading them took a lot of time, and this happened before creating the window. I need to think about how to solve it.

good luck with it

**Comment by zdm65477730** [comment]
Please have a try with below debug version, I think it can sovle the issue.
[NX-Activity-Log.zip](https://github.com/user-attachments/files/17779076/NX-Activity-Log.zip)

**Comment by NAEL2XD** [comment]
> Please have a try with below debug version, I think it can sovle the issue. [NX-Activity-Log.zip](https://github.com/user-attachments/files/17779076/NX-Activity-Log.zip)

```
[debug] Services started and Crul init finished!
[debug] Read config file finished!
[debug] Set language finished!
[debug] readPlayDataFromImport() enter
[debug] pdmqryGetAvailablePlayEventRange(), rc=0, totalEntries=296374
```

tried it, and yet a black screen

**Comment by zdm65477730** [comment]
OK, the buffer still not enough, please try again with this one:
[NX-Activity-Log.zip](https://github.com/user-attachments/files/17779787/NX-Activity-Log.zip)

**Comment by NAEL2XD** [comment]
> OK, the buffer still not enough, please try again with this one: [NX-Activity-Log.zip](https://github.com/user-attachments/files/17779787/NX-Activity-Log.zip)

```
[2024-11-15 19:56:17] Services started and Crul init finished!
[2024-11-15 19:56:17] Read config file finished!
[2024-11-15 19:56:17] Set language finished!
[2024-11-15 19:56:17] readPlayDataFromPdm() enter
[2024-11-15 19:56:17] readPlayDataFromImport() enter
[2024-11-15 19:56:17] readPlayDataFromImport() exit
[2024-11-15 19:56:17] pdmqryGetAvailablePlayEventRange(), rc=0, totalEntries=296374
```

**Comment by NAEL2XD** [comment]
and yes it still did a black screen

**Comment by zdm65477730** [comment]
The issue is clear now, I’ll fix it.

**Comment by zdm65477730** [comment]
[NX-Activity-Log.zip](https://github.com/user-attachments/files/17783248/NX-Activity-Log.zip)

Hope it works, if test passed, I'll release it soon.

**Comment by NAEL2XD** [comment]
OMGGGGG IT WORKEDDDD!!!!!!!! I CAN FINALLY BOOT UP!!! THANK YOU !!!!!

**Comment by NAEL2XD** [comment]
> 
> [NX-Activity-Log.zip](https://github.com/user-attachments/files/17783248/NX-Activity-Log.zip)
> 
> Hope it works, if test passed, I'll release it soon.

OMGGGGG IT WORKEDDDD!!!!!!!! IT FINALLY BOOT UP WITHOUT BLACK SCREEN!! THANK YOU !!!!!

**Comment by zdm65477730** [comment]
Great, I'll make a new release soon.

**Comment by NAEL2XD** [comment]
![20241116_143315.jpg](https://github.com/user-attachments/assets/6a43d61a-5bf2-4cb5-9eeb-612495a79b6b)
