### ISSUE TITLE
Japanese is not reflected　1.5.1

### ISSUE THREAD

**Issue by yyoossk** [zdm65477730/NX-Activity-Log#5]
Japanese is not reflected　1.5.1

**Comment by zdm65477730** [comment]
I have merged the pull request from you, it should have the Japanese lang fix:
repo: https://github.com/zdm65477730/NX-Activity-Log-Translations
commit-id: ff1e37e33136b8b83cec6a578e20d303d4ff6911

**Comment by yyoossk** [comment]
Still not translated into Japanese.
Please test it.
