### ISSUE TITLE
User profile replacement doesn't work

### ISSUE THREAD

**Issue by octopuserectus** [zdm65477730/NX-Activity-Log#7]
HOS: 18.1.0
AMS: 1.8.0

Once user page is selected with NX-Activity-Log replacement enabled, it makes the device unresponsive (power menu can be called but it doesn't work), doesn't produce AMS crash log, only forced reboot helps.

**Comment by zdm65477730** [comment]
Did you checked if the sysmodule created in contents folder?

**Comment by AlM2025** [comment]
Clear the folder config/NX-Activity-Log

**Comment by octopuserectus** [comment]
Apparently it was conflicting with the installed user page theme, sorry and thank you folks. I'll see myself out.
