### ISSUE TITLE
Total hours count

### ISSUE THREAD

**Issue by Shadas4free** [zdm65477730/NX-Activity-Log#8]
Your latest version has bug with wrong total hours counting when you sort your recent activity by year

**Comment by zdm65477730** [comment]
@Shadas4free could you show it with a picture?

**Comment by Shadas4free** [comment]
sure, here it is:

it count well when user has low playtime

![1 user low playtime](https://github.com/user-attachments/assets/4e74ba77-61b7-4b9b-808c-b9e554348b2a)

but when use have big playtime there is wrong number in total hours.

![2 user big playtime](https://github.com/user-attachments/assets/08dbc903-0216-4708-b4bc-a89b19cad9ba)

**Comment by zdm65477730** [comment]
@Shadas4free , yes, there is bug in recent activvity view.
Pleaes have a try with below debug version:
[NX-Activity-Log.zip](https://github.com/user-attachments/files/17790418/NX-Activity-Log.zip)

**Comment by Shadas4free** [comment]
I´ve tested your new version and here is the result. The playtime is much more inaccurate and it takes for 15 seconds when i switch from month view to year view. I´ve also noticed that month log has an inaccurate time to.

![activity2](https://github.com/user-attachments/assets/845d432a-231e-4b16-97a9-6092e12adf0a)
![activity](https://github.com/user-attachments/assets/e284647b-01b4-4e6e-a213-8b1d710ae84b)

**Comment by AlM2025** [comment]
Yes, I’m experiencing the same issue. It would be great if @zdm65477730 could address it. This issue is well-known and is already being discussed in the forums. NX-Activity-Log offers the best UI/UX-friendly activity analysis—no other app can match it.

**Comment by zdm65477730** [comment]
Sorry, I just fixed it in recent activity day view, now I fixed it in month and year view as well.
[NX-Activity-Log.zip](https://github.com/user-attachments/files/17801083/NX-Activity-Log.zip)

**Comment by AlM2025** [comment]
Thank you! It seems to be working correctly for me now.
@Shadas4free , could you please confirm if it's working on your end as well?

**Comment by zdm65477730** [comment]
OK, if it works well, I'll release it soon.

**Comment by Shadas4free** [comment]
I have still inaccurate time with your latest release. And when i switch to month view there is a big delay between loading another months(about 15 seconds) i will post screenshots when i come back home.

**Comment by Shadas4free** [comment]
So here is my result. This one is my real activity except the total time on the right upper corner
![386918631-08dbc903-0216-4708-b4bc-a89b19cad9ba](https://github.com/user-attachments/assets/129b1cb8-5137-481e-90cb-0b02aabebe7c)

and this one is with your latest release from this threat. Graph bars and total time is different.
![Clipboard01](https://github.com/user-attachments/assets/3ec08209-f966-4ef0-be9e-43f9ff14bfcf)

Here is video with extended loading:
https://www.mediafire.com/file/f1so6fskiajfsgf/20241119_173342.mp4/file

**Comment by zdm65477730** [comment]
@Shadas4free The total playtime of all the pervious release on the right upper corner did not include the playtime for all the hidden games, but the total playtime in graph bars did, so that's there is mismatch between them.

Now, I updated a bit and it looks like more reasonable, please try again:

[NX-Activity-Log.zip](https://github.com/user-attachments/files/17833222/NX-Activity-Log.zip)

**Comment by Shadas4free** [comment]
I do not have any hidden titels if you mean thorught settins in "hide" tab. I´ve never used this feature at all. I´ve tested  your latest build and some titles dissapear in list tittle. and the time in year filter is ok (expect total time) but in month and day filter it is still inaccurate. Maybe there is some problem in my activity log because 3 users using nitendo from 2020 so there is a lot of data. You can cllose this issue if others activity log is displaying properly and is problem only on me ;-)

**Comment by zdm65477730** [comment]
There are different behaviors between the two APIs in libnx which are used to fetch user game play data.
So, the play time data may inaccurate due to some unknown reason.

But I have tried to make most of scenarios keep the play time inaccurate by using the same API.
I'll release it soon.

**Comment by zdm65477730** [comment]
@Shadas4free , I think I have fixed the issue, you can try the latest release.
Please note, the game list in Recently view will only show the game you installed.
